NewSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizza.urls'))
]

pizza/urls.py
from django.urls import path

from . import views

app_name = 'pizza'
urlpatterns = [
    path('', views.index, name='index'),
    path('beverages/', views.beverages, name='beverages')
]

pizza/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name


class Ingredients(models.Model):
    ingredients = models.CharField(max_length=25, unique=True)

    class Meta:
        verbose_name = 'Ingredient'
        verbose_name_plural = 'Ingredients'
        ordering = ('ingredients',)

    def __str__(self):
        return self.ingredients


class Pizza(models.Model):
    pizza_name = models.CharField(max_length=30)
    pizza_img = models.ImageField(upload_to='images', null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    ingredients = models.ManyToManyField(Ingredients)

    class Meta:
        ordering = ('category', 'pizza_name')

    def __str__(self):
        return self.pizza_name


class Price(models.Model):
    small_pizza_price = models.DecimalField(max_digits=5, decimal_places=2)
    medium_pizza_price = models.DecimalField(max_digits=5, decimal_places=2)
    large_pizza_price = models.DecimalField(max_digits=5, decimal_places=2)
    pizza = models.OneToOneField(Category, on_delete=models.CASCADE)


class Weight(models.Model):
    small_pizza_weight = models.IntegerField(default=0)
    medium_pizza_weight = models.IntegerField(default=0)
    large_pizza_weight = models.IntegerField(default=0)
    pizza = models.OneToOneField(Pizza, on_delete=models.CASCADE)


class BeveragesCategory(models.Model):
    category_name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Beverages Categories'

    def __str__(self):
        return self.category_name


class BeveragesWeight(models.Model):
    weight = models.IntegerField(default=0, unique=True)

    class Meta:
        ordering = ('weight',)

    def __str__(self):
        return str(self.weight)


class BeveragesPrice(models.Model):
    price = models.IntegerField(default=0, unique=True)

    class Meta:
        ordering = ('price',)

    def __str__(self):
        return str(self.price)


class Beverages(models.Model):
    drink_name = models.CharField(max_length=50)
    drink_img = models.ImageField(upload_to='images_drinks_beverages', null=True)
    category = models.ForeignKey(BeveragesCategory, on_delete=models.CASCADE)
    price = models.ManyToManyField(BeveragesPrice)
    weight = models.ManyToManyField(BeveragesWeight)

    class Meta:
        verbose_name_plural = 'Beverages'

    def __str__(self):
        return self.drink_name

pizza/views.py
from django.shortcuts import render

from .models import Category, BeveragesCategory


def index(requests):
    context = {
        'category': Category.objects.all(),
    }
    return render(requests, 'pizza/index.html', context=context)


def beverages(requests):
    context = {
        'category': BeveragesCategory.objects.all(),
    }
    return render(requests, 'pizza/beverages.html', context=context)

pizza/templates/pizza/basefooter.html
<footer class="pt-4 my-md-5 pt-md-5 border-top text-center">
    <div class="row">
        <div class="col-12 col-md">
            <img class="mb-2" src="http://www.w3.org/2000/svg" alt="">
            <small class="d-block mb-3 text-muted">© 2020-2021</small>
        </div>
        <div class="col-6 col-md">
            <h5>КОНТАКТЫ</h5>
            <ul class="list-unstyled text-small">
                <li>Linkedin: <a href="https://www.linkedin.com/in/владислав-шинкарьов-25b53a1b6/" class="text-muted">Ссылка</a>
                </li>
                <li>E-mail: RoyalSam@ukr.net</li>
                <li>Номер телефона: (068)-90-07-931</li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Принимаем </h5>
            <svg width="1em" height="1em" viewBox="25" class="bi bi-credit-card" fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v1h14V4a1 1 0 0 0-1-1H2zm13 4H1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V7z"></path>
                <path d="M2 10a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-1z"></path>
            </svg>
            <svg width="1em" height="1em" viewBox="25" class="bi bi-cash" fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M15 4H1v8h14V4zM1 3a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H1z"></path>
                <path d="M13 4a2 2 0 0 0 2 2V4h-2zM3 4a2 2 0 0 1-2 2V4h2zm10 8a2 2 0 0 1 2-2v2h-2zM3 12a2 2 0 0 0-2-2v2h2zm7-4a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"></path>
            </svg>


        </div>
        <div class="col-6 col-md">
            <h5>DOMI PIZZA</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="https://media.dominos.ua/allergens_info/allergeny_rus.pdf">Информация по содержанию аллергенов</a></li>
            </ul>
        </div>
    </div>
</footer>

pizza/templates/pizza/basehead.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Domi Pizza</h5>
  <nav class="my-2 my-md-0 mr-md-3">
      <a class="btn btn-outline-secondary" href="{% url 'pizza:index' %}">Пицца</a>
    <a class="btn btn-outline-secondary" href="{% url 'pizza:beverages' %}">Напитки</a>
      <a class="btn btn-outline-secondary" href="#">Корзина</a>
  </nav>
</div>

pizza/templates/pizza/beverages.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <script src="{% static "vendor/js/jquery-3.3.1.slim.min.js" %}" defer></script>

    <script src="{% static "vendor/js/popper.min.js" %}" async></script>

    <link rel="stylesheet" href="{% static "vendor/css/bootstrap.min.css" %}">

    <script src="{% static "vendor/js/bootstrap.min.js" %}" defer></script>
    <meta charset="UTF-8">
    <title>Beverages</title>
</head>
<body>
{% include 'pizza/basehead.html' %}
<div class="container">
    {% for cat in category %}
        <h1 class="text-center">{{ cat.category_name }}</h1>
        <div class="row">
            {% for drink in cat.beverages_set.all %}
                <div class="col-sm-12 col-lg-6 pb-2">
                    <div class="card h-100 shadow">
                        <img class="card-img-top" src="{% static drink.drink_img %} " alt="{{ drink.drink_name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ drink.drink_name }}</h5>
                        </div>
                        <div class="card-footer">
                            <p>Size: {{ drink.weight.all|join:", " }}</p>
                            <p>Price: {{ drink.price.all|join:", " }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
    {% include 'pizza/basefooter.html' %}
</div>
</body>
</html>

pizza/templates/pizza/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <script src="{% static "vendor/js/jquery-3.3.1.slim.min.js" %}" defer></script>

    <script src="{% static "vendor/js/popper.min.js" %}" async></script>

    <link rel="stylesheet" href="{% static "vendor/css/bootstrap.min.css" %}">

    <script src="{% static "vendor/js/bootstrap.min.js" %}" defer></script>
    <meta charset="UTF-8">
    <title>Pizza</title>
</head>
<body>
{% include 'pizza/basehead.html' %}
<div class="container">
    {% for cat in category %}
        <h1 class="text-center">{{ cat.category_name }}</h1>
        <div class="row">
            {% for pizza in cat.pizza_set.all %}
                <div class="col-sm-12 col-lg-6 pb-2">
                    <div class="card h-100 shadow">
                        <img class="card-img-top" src="{% static pizza.pizza_img %} " alt="{{ pizza.pizza_name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ pizza.pizza_name }}</h5>
                            <p class="card-text">{{ pizza.ingredients.all|join:", " }}</p>
                        </div>
                        <div class="accordion" id="accordion{{ pizza.id }}Example">
                            <div class="card">
                                <div class="card-header" id="heading{{ pizza.id }}One">
                                    <h2 class="mb-0">
                                        <button class="btn btn-link text-secondary" data-toggle="collapse"
                                                data-target="#collapse{{ pizza.id }}One"
                                                aria-expanded="true" aria-controls="collapse{{ pizza.id }}One">
                                            Маленькая
                                        </button>
                                    </h2>
                                </div>
                                <div id="collapse{{ pizza.id }}One" class="collapse show"
                                     aria-labelledby="heading{{ pizza.id }}One"
                                     data-parent="#accordion{{ pizza.id }}Example">
                                    <div class="card-body">
                                        <h6>Вес: {{ pizza.weight.small_pizza_weight }}гр</h6>
                                        <h6>Цена: {{ cat.price.small_pizza_price }}</h6>
                                    </div>
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-header" id="heading{{ pizza.id }}Two">
                                    <h2 class="mb-0">
                                        <button class="btn btn-link collapsed text-secondary" data-toggle="collapse"
                                                data-target="#collapse{{ pizza.id }}Two"
                                                aria-expanded="false" aria-controls="collapse{{ pizza.id }}Two">
                                            Средняя
                                        </button>
                                    </h2>
                                </div>
                                <div id="collapse{{ pizza.id }}Two" class="collapse"
                                     aria-labelledby="heading{{ pizza.id }}Two"
                                     data-parent="#accordion{{ pizza.id }}Example">
                                    <div class="card-body">
                                        <h6>Вес: {{ pizza.weight.medium_pizza_weight }}гр</h6>
                                        <h6>Цена: {{ cat.price.medium_pizza_price }}</h6>
                                    </div>
                                </div>
                            </div>


                            <div class="card">
                                <div class="card-header" id="heading{{ pizza.id }}Three">
                                    <h2 class="mb-0">
                                        <button class="btn btn-link collapsed text-secondary" data-toggle="collapse"
                                                data-target="#collapse{{ pizza.id }}Three" aria-expanded="false"
                                                aria-controls="collapse{{ pizza.id }}Three">
                                            Большая
                                        </button>
                                    </h2>
                                </div>
                                <div id="collapse{{ pizza.id }}Three" class="collapse"
                                     aria-labelledby="heading{{ pizza.id }}Three"
                                     data-parent="#accordion{{ pizza.id }}Example">
                                    <div class="card-body">
                                        <h6>Вес: {{ pizza.weight.large_pizza_weight }}гр</h6>
                                        <h6>Цена: {{ cat.price.large_pizza_price }}</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
    {% include 'pizza/basefooter.html' %}
</div>
</body>
</html>